# Generated by Django 6.0.4 on 2026-05-08 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_app', '0002_silvertransaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='silvertransaction',
            old_name='total_amount',
            new_name='amount_toman',
        ),
        migrations.AddField(
            model_name='silverinventory',
            name='total_spent_toman',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='silverinventory',
            name='total_withdrawn_gr',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='silvertransaction',
            name='status',
            field=models.CharField(choices=[('DONE', 'انجام شده'), ('PENDING', 'در انتظار'), ('FAILED', 'ناموفق')], default='DONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='silvertransaction',
            name='amount_gr',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='silvertransaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'خرید'), ('SELL', 'فروش'), ('DEPOSIT', 'واریز وجه'), ('WITHDRAW', 'برداشت وجه')], max_length=15),
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('iban', models.CharField(blank=True, max_length=26, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_bank_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
