# Generated by Django 6.0.4 on 2026-05-08 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_app', '0003_rename_total_amount_silvertransaction_amount_toman_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='silvertransaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'خرید نقره'), ('SELL', 'فروش نقره'), ('CONVERT', 'تبدیل از ریال')], max_length=15),
        ),
    ]
