# Generated by Django 6.0.4 on 2026-05-07 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0004_alter_adminbankinfo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('category', models.CharField(choices=[('18_KARAT', '۱۸ عیار'), ('24_KARAT', '۲۴ عیار'), ('PARSIAN', 'پارسیان')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='وزن خالص (گرم)')),
                ('total_weight_with_fees', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='وزن نهایی با اجرت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس تحویل')),
                ('city', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('GOLD', 'پرداخت با طلا'), ('TOMAN', 'پرداخت نقدی')], max_length=10)),
                ('total_gold_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('total_toman_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'ثبت درخواست'), ('DELIVERED', 'تحویل شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_time', models.DecimalField(decimal_places=0, max_digits=20)),
                ('weight_at_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gold_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gold_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.product')),
            ],
        ),
    ]
