# Generated by Django 6.0.4 on 2026-05-07 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0006_giftcard_giftcardorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت هدف (تومان)')),
                ('alert_type', models.CharField(choices=[('ONCE', 'فقط یکبار اطلاع بده'), ('ALWAYS', 'هربار اطلاع بده')], default='ONCE', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
